services:
  app-frontend:
    build:
      context: ./app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app-service

  app-service:
    build:
      context: ./app-service
    ports:
      - "5000:5000"