name: Release 

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Semantic versioning pattern

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract and Parse version info from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - name: Registry Login (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.version }}
            ghcr.io/${{ github.repository }}:${{ env.version_major }}.${{ env.version_minor }}.${{ env.version_patch }}
            ghcr.io/${{ github.repository }}:${{ env.version_major }}.${{ env.version_minor }}.latest
            ghcr.io/${{ github.repository }}:${{ env.version_major }}.latest
            ghcr.io/${{ github.repository }}:latest
